server:
  port: 8080

spring:
  application:
    name: api-gateway

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4318

security:
  jwt:
    secret: dev-secret-please-change
